config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'model/carmodel'
  root to: 'pages#home'
  get "/contact-us", to: "pages#contactus"
  get "/about-us", to: "pages#aboutus"
  get "/news-&-media", to: "pages#newsandmedia"
  get "/test", to: "pages#test"
  get "/career", to: "pages#career"
  get "/dashboard", to: "pages#dashboard"
  get "/gallery", to: "pages#gallery"
  get "/ourbrands/eicher", to: "pages#eicher"
  get "/ourbrands/goldendragon", to: "pages#goldendragon"
  resources :makes, only: [:show, :new, :create], path: 'ourbrands'
  resources :categorys, only: [:show, :index]

  # resources :makes, only: [:show]
  resources :carmodels, only: [ :show, :new, :create, :index, :edit, :update ]
    authenticate :user do
      resources :vehicles
    end

  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
  end


end

app/models/make.rb
class Make < ApplicationRecord
  mount_uploader :logo, PhotoUploader
  has_many :carmodels, dependent: :destroy
  has_one :logo

end

app/controllers/makes_controller.rb
class MakesController < ApplicationController
  before_action :find_make, only: [:show, :update, :destroy, :edit, :create]

  def index
    @makes = Make.all
  end

  def show
    @models = Carmodel.where(make_id: @make.id)

  end

  def new
    @make = Make.new
  end

  def create
    if @make.save(make_params)
      respond_to do |format|
        format.html { redirect_to make_path(@make) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    end
  end

  private

  def make_params
    params.require(:make).permit(:name, :country)
  end

  def find_make
    @make ||= Make.find(params[:id])
  end

end

app/views/makes/show.html.erb
<div class="make-container" >
  <div class="title">
    <div class="secondary-title">
      <p>RANGE OF <%= @make.name.upcase %></p>
    </div>
  </div>

  <!-- Search -->
  <!-- <div class="search-field">
    <%= form_tag carmodels_path, method: :get, remote: true, id: "search-form" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find your vehicle",
        id: "input"
      %>
      <%= submit_tag "Search", id: "submit", class: "search-button" %>
    <% end %>
  </div> -->
  <!-- End Search -->

  <div class="product-holder">
    <% if @models.empty? == false %>
      <% @models.each do |model| %>
        <div class=" box vehicle page-box" data-toggle="modal" data-target="#myModal_<%= model.id %>">
          <div class="vehicle-title" >
            <p><%= model.name %></p>
          </div>
          <div class="vehicle-photo eicher-truck-photo">
            <%= cl_image_tag model.photo %>
          </div>
       </div>
       <%= render "shared/show_car_modal", carmodel: model %>
      <% end %>
    <% else %>
      <div class=" box vehicle page-box">
        <div class="secondary-title" >
          <p>No Stock for <%= @make.name.upcase %></p>
        </div>
      </div>
    <% end  %>
  </div>
</div>
<%# raise  %>




  <!--AJAX Search Form -->
<script>
  let formSelect = document.getElementById("search-form");
  let searchInput = document.getElementById("input");
  let submitButton = document.getElementById("submit");

  searchInput.addEventListener("keyup", (event) => {
    submitButton.click();
  });
</script>
<!-- End AJAX Search Form -->