config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'model/carmodel'
  root to: 'pages#home'
  get "/contact-us", to: "pages#contactus"
  get "/about-us", to: "pages#aboutus"
  get "/news-&-media", to: "pages#newsandmedia"
  get "/test", to: "pages#test"
  get "/career", to: "pages#career"
  get "/dashboard", to: "pages#dashboard"
  get "/gallery", to: "pages#gallery"
  get "/ourbrands/eicher", to: "pages#eicher"
  get "/ourbrands/goldendragon", to: "pages#goldendragon"
  resources :makes, only: [:show, :new, :create], path: 'ourbrands'
  resources :categorys, only: [:show, :index]

  # resources :makes, only: [:show]
  resources :carmodels, only: [ :show, :new, :create, :index, :edit, :update ]
    authenticate :user do
      resources :vehicles
    end

  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
  end


end

app/models/carmodel.rb
class Carmodel < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  visitable :ahoy_visit


  belongs_to :make
  belongs_to :classification
  belongs_to :subcategory
  belongs_to :fuel
  has_one :photo
  has_many :visits, class_name: "Ahoy::Visit"
  has_many :vehicles, dependent: :destroy


  include PgSearch
  pg_search_scope :search_by_name_and_category,
                  against: %i[name category],
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/controllers/carmodels_controller.rb
class CarmodelsController < ApplicationController
    before_action :find_model, only: [:show, :update, :destroy, :edit]

  def index
    @models = Carmodel.all
  end

  def show
    # @model = Carmodel.find(params[:carmodel_id])

  end
  def edit
    @makes = Make.all.to_a.map {|make| make }

  end

  def update
    if @model.update(model_params)
      respond_to do |format|
        format.html { redirect_to carmodel_path(@model), notice: 'Model has been Updated' }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    end

  end


  def new
    @model = Carmodel.new
    @makes = Make.all.to_a.map {|make| make }
  end

  def create
    @model = Carmodel.new(model_params)
    if @model.save
      respond_to do |format|
        format.html { redirect_to carmodel_path(@model), notice: 'Model has been Created' }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    end
  end


  private

  def find_model
    @model ||= Carmodel.find(params[:id])
  end

  def model_params
    params.require(:carmodel).permit(:name, :classification_id, :subcategory_id, :make_id, :fuel_id, :year, :power, :bodytype, :cargolength, :seats, :payload, :grossvw, :duty, :notes, :available, :new,  :photo )
  end
end

app/views/carmodels/edit.html.erb
<div class="container-booking" >
  <%= link_to dashboard_path, class: "secondary-button" do %>
    <i class="fas fa-hand-point-left fa-3x"></i>
  <% end %>
  <div class="booking-box">
    <div class="title">
        <div class="secondary-title" style="margin: 0">
          <p>CREATE A NEW MODEL</p>
        </div>
      </div>
    <%= simple_form_for(@model) do |f| %>
      <% @model.errors.each do |attr, msg| %>
        <div class="error-messages">
          <p>Please review your entries</p>
         <li> <%= @model.errors.full_messages_for(attr).first if @model.errors[attr].first == msg %></li>
        </div>
      <% end %>
      <div class="booking-box-details">
        <div class="form-divider">
          <div class="form-section-title">
            <div class="form-title">
              <p>Main Detail</p>
            </div>
          </div>

          <div class="form-breaker">
            <div class="form-inputs">
              <%= f.input :name %>
            </div>
            <div class="form-inputs">
              <%= f.input :classification_id, collection: Classification.order(:name).pluck(:name, :id), prompt: "Choose a Class"  %>
            </div>
            <div class="form-inputs">
              <%= f.input :subcategory_id, collection: Subcategory.order(:name).pluck(:name, :id), prompt: "Choose a sub-category"  %>
            </div>
            <div class="form-inputs">
              <%= f.input :make_id, collection: Make.order(:name).pluck(:name, :id), prompt: "Choose a The Make"    %>
            </div>
            <div class="form-inputs">
              <%= f.input :fuel_id, collection: Fuel.order(:name).pluck(:name, :id), prompt: "Choose Fuel Type"   %>
            </div>
            <div class="form-inputs">
              <%= f.input :year %>
            </div>
          </div>
        </div>


        <div class="form-divider">
          <div class="form-section-title">
            <div class="form-title">
              <p>Technical Detail</p>
            </div>
          </div>

          <div class="form-breaker">

            <div class="form-inputs">
              <%= f.input :power %>
            </div>
            <div class="form-inputs">
              <%= f.input :bodytype %>
            </div>
            <div class="form-inputs">
              <%= f.input :cargolength, collection: 1..60  %>
            </div>
            <div class="form-inputs">
              <%= f.input :seats, collection: 1..60  %>
            </div>
            <div class="form-inputs">
              <%= f.input :payload, collection: 1..60  %>
            </div>
            <div class="form-inputs">
              <%= f.input :grosvw, collection: 0..30  %>
            </div>
            <div class="form-inputs">
              <%= f.input :duty, collection: 18..60  %>
            </div>
          </div>
        </div>

        <div class="form-divider">
          <div class="form-section-title">
            <div class="form-title">
              <p>Other Detail</p>
            </div>
          </div>

          <div class="form-breaker">

            <div class="form-inputs">
              <%= f.input :notes %>
            </div>
            <div class="form-inputs" id="checkme">
              <%= f.input :available, boolean_style: :inline %>
            </div>
            <div class="form-inputs" id="checkme">
              <%= f.input :new, boolean_style: :inline %>
            </div>
            <div class="form-inputs">
              <%= f.input :photo, as: :file %>
            </div>
          </div>
        </div>

        <div class="form-actions">
          <div class="booking-update-btn">
            <%= f.button :submit, class: "form-button", :confirm => 'Are All details correct?' %>
            <%# raise %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/carmodels/index.js.erb
function refreshCards(innerHTML) {
  newCardsContainer = document.querySelector(".product-holder")
  newCardsContainer.innerHTML = innerHTML;
 }

refreshCards('<%= j render "vehicles", carmodels: @models %>');

app/views/carmodels/new.html.erb
<div class="container-booking" >
  <%= link_to dashboard_path, class: "secondary-button" do %>
    <i class="fas fa-hand-point-left fa-3x"></i>
  <% end %>
  <div class="booking-box">
    <div class="title">
        <div class="secondary-title" style="margin: 0">
          <p>CREATE A NEW MODEL</p>
        </div>
      </div>
    <%= simple_form_for(@model) do |f| %>
      <% @model.errors.each do |attr, msg| %>
        <div class="error-messages">
          <p>Please review your entries</p>
         <li> <%= @model.errors.full_messages_for(attr).first if @model.errors[attr].first == msg %></li>
        </div>
      <% end %>
      <div class="booking-box-details">
        <div class="form-divider">
          <div class="form-section-title">
            <div class="form-title">
              <p>Main Detail</p>
            </div>
          </div>

          <div class="form-breaker">
            <div class="form-inputs">
              <%= f.input :name %>
            </div>
            <div class="form-inputs">
              <%= f.input :classification_id, collection: Classification.order(:name).pluck(:name, :id), prompt: "Choose a Class"  %>
            </div>
            <div class="form-inputs">
              <%= f.input :subcategory_id, collection: Subcategory.order(:name).pluck(:name, :id), prompt: "Choose a sub-category"  %>
            </div>
            <div class="form-inputs">
              <%= f.input :make_id, collection: Make.order(:name).pluck(:name, :id), prompt: "Choose a The Make"    %>
            </div>
            <div class="form-inputs">
              <%= f.input :fuel_id, collection: Fuel.order(:name).pluck(:name, :id), prompt: "Choose Fuel Type"   %>
            </div>
            <div class="form-inputs">
              <%= f.input :year %>
            </div>
          </div>
        </div>


        <div class="form-divider">
          <div class="form-section-title">
            <div class="form-title">
              <p>Technical Detail</p>
            </div>
          </div>

          <div class="form-breaker">

            <div class="form-inputs">
              <%= f.input :power %>
            </div>
            <div class="form-inputs">
              <%= f.input :bodytype %>
            </div>
            <div class="form-inputs">
              <%= f.input :cargolength, collection: 1..60  %>
            </div>
            <div class="form-inputs">
              <%= f.input :seats, collection: 1..60  %>
            </div>
            <div class="form-inputs">
              <%= f.input :payload, collection: 1..60  %>
            </div>
            <div class="form-inputs">
              <%= f.input :grosvw, collection: 0..30  %>
            </div>
            <div class="form-inputs">
              <%= f.input :duty, collection: 18..60  %>
            </div>
          </div>
        </div>

        <div class="form-divider">
          <div class="form-section-title">
            <div class="form-title">
              <p>Other Detail</p>
            </div>
          </div>

          <div class="form-breaker">

            <div class="form-inputs">
              <%= f.input :notes %>
            </div>
            <div class="form-inputs" id="checkme">
              <%= f.input :available, boolean_style: :inline %>
            </div>
            <div class="form-inputs" id="checkme">
              <%= f.input :new, boolean_style: :inline, input_html: {id: "select2"} %>
            </div>
              <div class="form-inputs">
                <%= f.input :mileage %>
              </div>
            <div class="form-inputs">
              <%= f.input :photo, as: :file %>
            </div>
          </div>
        </div>

        <div class="form-actions">
          <div class="booking-update-btn">
            <%= f.button :submit, class: "form-button", :confirm => 'Are All details correct?' %>
            <%# raise %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/carmodels/show.html.erb
<div class="make-container" >
  <div class="title">
      <div class="secondary-title">
        <p> <%= Make.find(@model.make.id).name %> - <%= @model.name %>, <%= @model.subcategory.category.name %> <%= @model.subcategory.name %> </p>
      </div>
    </div>

  <div class="product-holder">
      <div class=" box vehicle page-box" >
        <div class="vehicle-title" >
          <p><%= @model.name %></p>
        </div>
        <div class="vehicle-photo eicher-truck-photo">
          <%= cl_image_tag @model.photo %>
        </div>
     </div>
     <%= link_to "Edit Model", edit_carmodel_path, class: 'search-button' %>
  </div>
</div>

app/views/carmodels/vehicles.html.erb
<div class="product-holder">
    <% @models.each do |model| %>
      <div class=" box vehicle page-box" data-toggle="modal" data-target="#myModal_<%= model.id %>">
        <div class="vehicle-title" >
          <p><%= model.name %></p>
        </div>
        <div class="vehicle-photo eicher-truck-photo">
          <%= cl_image_tag model.photo %>
        </div>
     </div>
     <%= render "shared/show_car_modal", carmodel: model %>
    <% end  %>
  </div>
</div>