config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'model/carmodel'
  root to: 'pages#home'
  get "/contact-us", to: "pages#contactus"
  get "/about-us", to: "pages#aboutus"
  get "/news-&-media", to: "pages#newsandmedia"
  get "/test", to: "pages#test"
  get "/career", to: "pages#career"
  get "/dashboard", to: "pages#dashboard"
  get "/gallery", to: "pages#gallery"
  get "/ourbrands/eicher", to: "pages#eicher"
  get "/ourbrands/goldendragon", to: "pages#goldendragon"
  resources :makes, only: [:show, :new, :create], path: 'ourbrands'
  resources :categorys, only: [:show, :index]

  # resources :makes, only: [:show]
  resources :carmodels, only: [ :show, :new, :create, :index, :edit, :update ]
    authenticate :user do
      resources :vehicles
    end

  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carmodel.rb
class Carmodel < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  visitable :ahoy_visit


  belongs_to :make
  belongs_to :classification
  belongs_to :subcategory
  belongs_to :fuel
  has_one :photo
  has_many :visits, class_name: "Ahoy::Visit"
  has_many :vehicles, dependent: :destroy


  include PgSearch
  pg_search_scope :search_by_name_and_category,
                  against: %i[name category],
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :subcategorys , dependent: :destroy
  has_many :carmodels, through: :subcategories
end

app/models/classification.rb
class Classification < ApplicationRecord
  has_many :carmodels
end

app/models/fuel.rb
class Fuel < ApplicationRecord
  has_many :carmodels,  dependent: :destroy
end

app/models/make.rb
class Make < ApplicationRecord
  mount_uploader :logo, PhotoUploader
  has_many :carmodels, dependent: :destroy
  has_one :logo

end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
  has_many :carmodels,  dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :classes
  has_one :photo



  def full_name
    first_name + " " + last_name
  end
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :carmodel
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  def require_admin
    # depending on your auth, something like...
    redirect_to root_path unless current_user && current_user.admin?
  end

end

app/controllers/carmodels_controller.rb
class CarmodelsController < ApplicationController
    before_action :find_model, only: [:show, :update, :destroy, :edit]

  def index
    @models = Carmodel.all
  end

  def show
    # @model = Carmodel.find(params[:carmodel_id])

  end
  def edit
    @makes = Make.all.to_a.map {|make| make }

  end

  def update
    if @model.update(model_params)
      respond_to do |format|
        format.html { redirect_to carmodel_path(@model), notice: 'Model has been Updated' }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    end

  end


  def new
    @model = Carmodel.new
    @makes = Make.all.to_a.map {|make| make }
  end

  def create
    @model = Carmodel.new(model_params)
    if @model.save
      respond_to do |format|
        format.html { redirect_to carmodel_path(@model), notice: 'Model has been Created' }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    end
  end


  private

  def find_model
    @model ||= Carmodel.find(params[:id])
  end

  def model_params
    params.require(:carmodel).permit(:name, :classification_id, :subcategory_id, :make_id, :fuel_id, :year, :power, :bodytype, :cargolength, :seats, :payload, :grossvw, :duty, :notes, :available, :new,  :photo )
  end
end

app/controllers/categorys_controller.rb
class CategorysController < ApplicationController
  def index
    @categorys = Category.all

  end
end

app/controllers/fuels_controller.rb
class FuelsController < ApplicationController
end

app/controllers/makes_controller.rb
class MakesController < ApplicationController
  before_action :find_make, only: [:show, :update, :destroy, :edit, :create]

  def index
    @makes = Make.all
  end

  def show
    @models = Carmodel.where(make_id: @make.id)

  end

  def new
    @make = Make.new
  end

  def create
    if @make.save(make_params)
      respond_to do |format|
        format.html { redirect_to make_path(@make) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    end
  end

  private

  def make_params
    params.require(:make).permit(:name, :country)
  end

  def find_make
    @make ||= Make.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_action :authenticate_user!, only: :dashboard

  def home
    @makes = Make.all
  end

  def test

  end

  def dashboard
    @commercial = Classification.where(name: "Commercial")
    @retail = Classification.where(name: "Retail")
  end


  def gallery
    @vehicles = Carmodel.all
    @lmd = Subcategory.where(name: "Light & Medium Duty")
    @staff = Subcategory.where(name: "Staff")
    @school = Subcategory.where(name: "School")
    @city = Subcategory.where(name: "City")
    @coach = Subcategory.where(name: "Coach")
    @hdv = Subcategory.where(name: "Heavy Duty")
    @tipper = Subcategory.where(name: "Tipper")
    @medical = Subcategory.where(name: "Medical")
    @firetruck = Subcategory.where(name: "Fire Truck")
    @police = Subcategory.where(name: "Police")
    @army = Subcategory.where(name: "Army")
    @compactsuv = Subcategory.where(name: "Compact SUV")
    @luxsuv = Subcategory.where(name: "Luxury SUV")
    @luxsedan = Subcategory.where(name: "Luxury Sedan")
    @sports = Subcategory.where(name: "Sports")
    @pickup = Subcategory.where(name: "Pickup")
    @hatchback = Subcategory.where(name: "Hatchback")

  end

  def eicher
    # if params[:query].present?
    #   @models = Carmodel.where(name: 'Eicher').search_by_name_and_category(params[:query])
    #   respond_to do |format|
    #     format.html { render eicher_path }
    #     format.js
    #   end
    # else
    #   @models = Carmodel.where(available: true)
    # end

    # @make = Make.where(name: 'Eicher')

    # @models = Carmodel.all
  end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
end

app/controllers/subcategorys_controller.rb
class SubcategorysController < ApplicationController

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :find_vehicle, only: [:show, :update, :destroy, :edit]


  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    if @vehicle.save
      respond_to do |format|
        format.html { redirect_to vehicle_path(@vehicle), notice: 'vehicle has been Created' }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    end
  end

  def show
    @vehicle = Vehicle.find(params[:id])

  end

  def index
    @vehicles = Vehicle.all
  end


  private

  def find_vehicle
    @vehicle ||= Vehicle.find(params[:id])
  end

  def vehicle_params
    params.require(:vehicle).permit(:carmodel_id, :engine_number, :purchase_price, :freight_cost, :other_cost, :accessories, :photo, :color, :mileage, :fuel_id, :year, :gear, :aircon)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%# javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <% if action_name == "home" %>
      <%= render 'shared/navbar' %>
    <% else %>
      <%= render 'shared/navbar_pages' %>
    <% end %>
    <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= yield :after_js %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="dashboard-conatiner">
  <div class="dashboard-side-nav" id="sidebar">
    <div class="dashnav-items-holder">
      <div class="dashnav-item" id="user">
        <div class="user-info" >
          <div class="user-image">
            <%= cl_image_tag current_user.photo, class: 'dash-avatar' %>
          </div>
          <div class="user-name">
            <p> <%= current_user.full_name %></p>
          </div>
        </div>
      </div>
      <div class="dashnav-item">
        <div class="user-type">
          <% if current_user.admin? %>
            <p>Super Admin Access</p>
          <% else %>
            <p>Sales Staff</p>
          <% end %>
        </div>
      </div>

      <div class="dashnav-item">
        <div class="link-item">
          <div class="link-icon">
            <i class="fas fa-chart-bar"></i>
          </div>
          <div class="link-name">
            <p> Blazer Dashboard</p>
          </div>
          <%= link_to blazer_path do %>
            <div class="link-arrow">
              <i class="fas fa-arrow-circle-right"></i>
            </div>
          <% end %>
        </div>
      </div>
      <div class="dashnav-item">
        <div class="link-item">
          <div class="link-icon">
            <i class="fas fa-car"></i>
          </div>
          <div class="link-name">
             <p>New Model</p>
          </div>
          <%= link_to new_carmodel_path do %>
            <div class="link-arrow">
              <i class="fas fa-arrow-circle-right"></i>
            </div>
          <% end %>
        </div>
      </div>

      <div class="dashnav-item">
        <div class="link-item">
          <div class="link-icon">
            <i class="fas fa-car-side"></i>
          </div>
          <div class="link-name">
             <p>New Vehicle</p>
          </div>
          <%= link_to new_vehicle_path do %>
            <div class="link-arrow">
              <i class="fas fa-arrow-circle-right"></i>
            </div>
          <% end %>
        </div>
      </div>


    </div>
    <!-- <div class="sidenav-buttons-holder">
      <div class="list-group border-0 text-center text-md-left commercial">
        <a href="#menu1" class="list-group-item d-inline-block collapsed show-border" data-toggle="collapse" aria-expanded="false"><i class="fa fa-dashboard"></i> <span class=" d-md-inline">item 1</span> </a>
        <div class="collapse" id="menu1" data-parent="#sidebar">
          <a href="#menu1sub1" class="list-group-item" data-toggle="collapse" aria-expanded="false"> <i class="fas fa-bus-alt fa-2x"></i> Buses</a>
          <div class="collapse" id="menu1sub1" data-parent="#menu1">
            <a class="list-group-item smaller" data-parent="#menu1sub1" onclick="displayStaffBus()">Staff</a>
            <a class="list-group-item smaller" data-parent="#menu1sub1" onclick="displaySchoolBus()" >School</a>
            <a class="list-group-item smaller" data-parent="#menu1sub1" onclick="displayCityBus()">City</a>
            <a class="list-group-item smaller" data-parent="#menu1sub1" onclick="displayCoachBus()">Coach</a>
          </div>
        </div>
        <div class="collapse" id="menu1" data-parent="#sidebar">
          <a href="#menu1sub2" class="list-group-item" data-toggle="collapse" aria-expanded="false"><i class="fas fa-truck-moving fa-2x"></i> Trucks</a>
          <div class="collapse" id="menu1sub2" data-parent="#menu1">
            <p class="list-group-item smaller" data-parent="#menu1sub2" onclick="displayLmd()">Light & Medium Duty</p>
            <p class="list-group-item smaller" data-parent="#menu1sub2" onclick="displayHdv()">Heavy Duty</p>
            <p class="list-group-item smaller" data-parent="#menu1sub2" onclick="displayTipper()">Tipper</p>
          </div>
        </div>
        <div class="collapse" id="menu1" data-parent="#sidebar">
          <a href="#menu1sub3" class="list-group-item" data-toggle="collapse" aria-expanded="false"><i class="fas fa-ambulance fa-2x"></i> Specialist</a>
          <div class="collapse" id="menu1sub3" data-parent="#menu1">
              <a class="list-group-item smaller" data-parent="#menu1sub3" onclick="displayAmbulence()">Ambulence</a>
              <a class="list-group-item smaller" data-parent="#menu1sub3" onclick="displayFireTruck()">Fire Truck</a>
          </div>
        </div>
      </div>
      <div class="list-group border-0 text-center text-md-left retail">
        <a href="#menu2" class="list-group-item d-inline-block collapsed show-border" data-toggle="collapse" aria-expanded="false"><i class="fa fa-dashboard"></i> <span class=" d-md-inline">item 2</span> </a>
        <div class="collapse" id="menu2" data-parent="#sidebar">
            <a href="#menu2sub1" class="list-group-item" data-toggle="collapse" aria-expanded="false"><i class="fas fa-truck-monster fa-2x"></i>SUVs </a>
            <div class="collapse" id="menu2sub1" data-parent="#menu2">
              <a class="list-group-item smaller" data-parent="#menu2sub1" onclick="displayLuxSuv()">Luxury Suv</a>
              <a class="list-group-item smaller" data-parent="#menu2sub1" onclick="displayCompactSuv()">Compact Suv</a>
            </div>
        </div>
        <div class="collapse" id="menu2" data-parent="#sidebar">
            <a href="#menu2sub2" class="list-group-item" data-toggle="collapse" aria-expanded="false"><i class="fas fa-car-side fa-2x"></i>Sedans </a>
            <div class="collapse" id="menu2sub2" data-parent="#menu2">
              <a class="list-group-item smaller" data-parent="#menu2sub2" onclick="displayLuxSedan()">Luxury Sedans</a>
              <a href="#" class="list-group-item smaller" data-parent="#menu2sub2">Sports</a>
            </div>
        </div>
        <div class="collapse" id="menu2" data-parent="#sidebar">
            <a href="#menu2sub3" class="list-group-item" data-toggle="collapse" aria-expanded="false"><i class="fas fa-truck-pickup fa-2x"></i>Others </a>
            <div class="collapse" id="menu2sub3" data-parent="#menu2">
              <a href="#" class="list-group-item smaller" data-parent="#menu2sub3">Pick-up</a>
              <a href="#" class="list-group-item smaller" data-parent="#menu2sub3">Hatchback</a>
            </div>
        </div>

      </div>
      <div class="list-group border-0 text-center text-md-left brands">
        <a href="#menu3" class="list-group-item d-inline-block collapsed show-border" data-toggle="collapse" aria-expanded="false"><i class="fa fa-dashboard"></i> <span class=" d-md-inline">item 3</span> </a>
        <div class="collapse" id="menu3" data-parent="#sidebar">
            <a href="#menu3sub1" class="list-group-item" data-toggle="collapse" aria-expanded="false">Eicher <img src="https://res.cloudinary.com/durtng53m/image/upload/v1592390519/Screenshot_2020-06-17_at_14-removebg-preview_2.png" style="width: 40%"></a>
            <a href="#menu3sub2" class="list-group-item" data-toggle="collapse" aria-expanded="false">Golden Dragon <img src="https://res.cloudinary.com/durtng53m/image/upload/v1593107217/unnamed__4_-removebg-preview.png" style="width: 20%" ></a>
            <a href="#menu3sub2" class="list-group-item" data-toggle="collapse" aria-expanded="false">Toyota <img src="https://res.cloudinary.com/durtng53m/image/upload/v1592381014/toyota.png" style="width: 30%" ></a>
            <a href="#menu3sub2" class="list-group-item" data-toggle="collapse" aria-expanded="false">Land Rover<img src="https://res.cloudinary.com/durtng53m/image/upload/v1592392119/png-land-rover-logo-car-brand-business-land-rover-text-label-trademark-service-clipart-removebg-preview.png" style="width: 40%" ></a>
            <a href="#menu3sub2" class="list-group-item" data-toggle="collapse" aria-expanded="false"> Mercedes <img src="https://res.cloudinary.com/durtng53m/image/upload/v1592392110/862px-Mercedes-Logo-removebg-preview.png" style="width: 20%" ></a>

        </div>

      </div>

    </div> -->
  </div>
  <div class="dashboard">

    <div class="dash-items-holder">
      <div class="dashboard-items">
        <div class="dash-item">
          <div class="item-icon blue">
            <i class="fas fa-truck"></i>
          </div>
          <div class="item-info">
            <div class="item-title">
              <p> <%= Carmodel.where(classification: @commercial).count %> </p>
            </div>
            <div class="item-content">
              <p>Commercial Models</p>
            </div>
          </div>
        </div>
        <div class="dash-item">
          <div class="item-icon yellow">
            <i class="fas fa-car"></i>
          </div>
          <div class="item-info">
            <div class="item-title">
              <p> <%= Carmodel.where(classification: @retail).count %> </p>
            </div>
            <div class="item-content">
              <p>Retail Models</p>
            </div>
          </div>
        </div>
        <%= link_to vehicles_path do%>
          <div class="dash-item">
            <div class="item-icon yellow">
              <i class="fas fa-car"></i>
            </div>
            <div class="item-info">
              <div class="item-title">
                <p> <%= Vehicle.all.count %> </p>
              </div>
              <div class="item-content">
                <p>Vehicle Available</p>
              </div>
            </div>
          </div>
        <% end %>

        <div class="dash-item">
          <div class="item-icon blue">
            <i class="fas fa-users"></i>
          </div>
          <div class="item-info">
            <div class="item-title">
              <p> <%= User.all.count %> </p>
            </div>
            <div class="item-content">
              <p>Staff</p>
            </div>
          </div>
        </div>

      </div>

      <% if current_user.admin == true %>
        <div class="dashboard-admin-items ">
          <div class="website-items">
            <div class="dash-item1 blue">
              <div class="item-icon ">
                <i class="fas fa-laptop"></i>
              </div>
              <div class="item-info">
                <div class="item-number">
                  <p> <%= Ahoy::Visit.all.count %> </p>
                </div>
                <div class="item-content">
                  <p>Website Visits</p>
                </div>
              </div>
            </div>
            <div class="dash-item1 yellow">
              <div class="item-icon">
                <i class="fas fa-mouse"></i>
              </div>
              <div class="item-info">
                <div class="item-number">
                  <p> <%= Ahoy::Event.all.count %> </p>
                </div>
                <div class="item-content">
                  <p>Website Clicks</p>
                </div>
              </div>
            </div>
           </div>
          <div class="dash-graphs">
            <div class="dash-item-graph">
              <div class="table-title">
                <p>Devise Access</p>
              </div>
              <div class="item-info">
                <div class="item-chart">
                  <%= pie_chart Ahoy::Visit.group(:device_type).count,  colors: ["#274972", "#AB964B"] %>
                </div>
              </div>
            </div>
            <div class="dash-item-graph">
              <div class="table-title">
                <p>Referring Domain</p>
              </div>
              <div class="item-info">
                <div class="item-chart">
                  <%= pie_chart Ahoy::Visit.group(:referring_domain ).count,  colors: ["#274972", "#AB964B"] %>
                </div>
              </div>
            </div>
            <div class="dash-item-graph">
              <div class="table-title">
                <p>Visit By City</p>
              </div>
              <div class="item-info">
                <div class="item-chart">
                  <%= pie_chart Ahoy::Visit.group(:city).count,  colors: ["#274972", "#AB964B"] %>
                </div>
              </div>
            </div>
          </div>

          <div class="dash-graphs-large">
            <div class="dash-item-graph" style="width: 100%">
              <div class="table-title">
                <p>Visits Per/Day</p>
              </div>
              <div class="item-info">
                <div class="item-chart">
                  <%= line_chart Ahoy::Visit.group_by_day(:started_at).count %>

                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>


    </div>
  </div>
</div>

app/views/pages/eicher.html.erb
<div class="make-container" >
  <div class="title">
      <div class="secondary-title">
        <p>RANGE OF EICHER PRODUCTS</p>
      </div>
    </div>

  <div class="product-holder">
    <% @models.each do |model| %>
      <div class=" box vehicle page-box" data-toggle="modal" data-target="#myModal_<%= model.id %>">
        <div class="vehicle-title" >
          <p><%= model.name %></p>
        </div>
        <div class="vehicle-photo eicher-truck-photo">
          <%= cl_image_tag model.photo %>
        </div>
     </div>
     <%= render "shared/show_car_modal", carmodel: model %>
    <% end  %>
  </div>
</div>
<%# raise  %>

app/views/pages/test.html.erb
<div class="box" style="height: 100vh; padding-top: 30%">

  <% @dragon = Make.find(30)  %>
  <% @vehicles = Carmodel.where(make_id: @dragon.id).each do |vehicle| %>
    <div class=" box vehicle page-box gallery-box " >
      <div class="vehicle-title" >
          <h1><%= vehicle.name %></h1>
      </div>
      <div class="vehicle-photo gallery-box-photo">
        <%= cl_image_tag vehicle.make.logo %>
      </div>
   </div>
  <% end %>
    <%# Carmodel.where(Make.where(name = "Golden Dragon")) %>
</div>

app/views/shared/_afri_branch_modal.html.erb
<div id="afri_branch_modal" class="modal fade" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-body">
      <div class="modal-content">
        <div><h1>test</h1></div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class=" nav-content fixed-top navbar-afri">
   <div class="nav-picture">
    <img src="https://res.cloudinary.com/durtng53m/image/upload/v1592297252/Screenshot_2020-06-14_at_16.23_2.png" alt="">
  </div>
  <div class=" navbar navbar-expand-sm navbar-light nav-content navbar-none-white">
      <%= link_to root_path, class: "navbar-brand" do %>
            <img src="https://res.cloudinary.com/durtng53m/image/upload/v1592226847/3_LOGO-afriltd.png" id="nav-logo">
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <div class="nav-main-items">
            <li class="nav-item">
              <p><%= link_to "ABOUT US", about_us_path %></p>
            </li>

            <li class="nav-item dropdown">
              <p class="dropdown-toggle" id="navbarDropdown" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"> OUR BRANDS </p>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <% @makes.each do |make| %>
                  <%= link_to make.name, make_path(make),
                      class: "dropdown-item black" %>
                <% end %>
              </div>
            </li>
            <li class="nav-item">
              <p><%= link_to "VEHICLES", gallery_path %></p>
            </li>
            <li class="nav-item">
              <p><%= link_to "CAREERS", career_path %></p>
            </li>
            <li class="nav-item">
              <p><%= link_to "CONTACT US", contact_us_path %></p>
            </li>
            <% if user_signed_in? %>
              <li class="nav-item">
                  <%= link_to "Dashboard", dashboard_path %>
              </li>
              <li class="nav-item">
                  <%= link_to "Edit account", edit_user_registration_path(current_user)  %>
              </li>
              <li class="nav-item">
                  <%= link_to "Log out", destroy_user_session_path, method: :delete %>
              </li>
            <% end %>
          </div>
        </ul>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

  var elmnt2 = document.getElementById("footerid")
  function scrollToBottom() {
    elmnt2.scrollIntoView({behavior: "smooth"}); // Bottom
  }
</script>

</div>

app/views/shared/_navbar_pages.html.erb
<div class=" nav-content fixed-top navbar-afri">
   <div class="nav-picture">
    <img src="https://res.cloudinary.com/durtng53m/image/upload/v1592297252/Screenshot_2020-06-14_at_16.23_2.png" alt="">
  </div>
  <div class=" navbar navbar-expand-sm navbar-light nav-content " id="navbar-two-white">
      <%= link_to root_path, class: "navbar-brand" do %>
            <img src="https://res.cloudinary.com/durtng53m/image/upload/v1592226847/3_LOGO-afriltd.png" id="nav-logo">
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <div class="nav-main-items">
            <li class="nav-item">
              <p><%= link_to "ABOUT US", about_us_path %></p>
            </li>

            <li class="nav-item dropdown">
              <p class="dropdown-toggle" id="navbarDropdown" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> OUR BRANDS </p>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <% Make.all.each do |make| %>
                  <%= link_to make.name, make_path(make),
                      class: "dropdown-item black" %>
                <% end %>
                <%# raise %>
              </div>
            </li>
            <li class="nav-item">
              <p><%= link_to "VEHICLES", gallery_path %></p>
            </li>
            <li class="nav-item">
              <p><%= link_to "CAREERS", career_path %></p>
            </li>
            <li class="nav-item">
              <p><%= link_to "CONTACT US", contact_us_path %></p>
            </li>
          </div>
        </ul>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

  var elmnt2 = document.getElementById("footerid")
  function scrollToBottom() {
    elmnt2.scrollIntoView({behavior: "smooth"}); // Bottom
  }
</script>

</div>